package com.app.sanad.util

const val USERS = "Users"
const val PARTNERS = "Partners"
const val USER = "user"
const val USER_PROFILE = "profile"
const val SUPPORTER = "supporter"
const val USER_NAME = "userName"
const val USER_IMAGE = "userImage"
const val PASSWORD = "password"
const val AGE_GROUP = "ageGroup"
const val GENDER = "gender"
const val INVITATION_CODE = "invitationCode"
const val NAME = "name"
const val IS_FIRST_TIME = "isFirstTime"
const val IS_USER_LOGGED = "isUserLogged"
const val IS_SECOND_TIME = "isSecondTime"
const val TYPE_OF_USER = "typeOfUser"
const val USER_EMAIL = "email"
const val USER_IDEAS = "user_idea"
const val RELIGION = "religion"
const val LANGUAGE = "language"
const val ENGLISH_KEY = "en"
const val ARABIC_KEY = "ar"
const val STATUS = "status"
const val CURRENT_DAY = "CurrentTask"
const val PARTNER_PROFILE = "partnerProfile"

const val ARTICLE = "article"
const val VIDEO = "video"
const val COMMON_CONTENT = "commonContent"
const val Customized_CONTENT = "customizedContent"
const val SUPPLICATIONS = "Supplications"

const val LIBRARY_CONTENTS = "library_contents"

const val SHARING= "sharing"
const val PROGRAM= "program"
const val CHATS = "chats"
const val LIBRARY = "library"
const val GRATITUDE = "Gratitude"
const val   POSTS = "posts"

const val ENCOURAGEMENT_CHANNEL_ID ="encouragementChannelId"
const val CALENDER_CHANNEL_ID ="calenderChannelId"
const val SCHEDULING_TIME ="schedulingTime"

// Params for Analytics

const val  PRE_MOOD_TRACKING_DURATION =   "pre_assessment_engagement"
const val  PRE_MOOD_TRACKING_COMPLETION = "pre_assessment_completed"
const val  CONTENT_COMPLETED = "content_completed"
const val  CONTENT_ENGAGEMENT = "content_engagement"
const val TEXT_TO_SPEECH = "tts_played"
const val CHALLENGES_ENGAGEMENT = "challenges_engagement"
const val CHALLENGING_COMPLETED = "challenge_completed"
const val CHALLENGE_SELECTED = "challenge_selected"
const val DailyProgramEngagement = "daily_program_engagement"
const val POST_ASSESSMENT_COMPLETED = "post_assessment_completed"
const val POST_ASSESSMENT_ENGAGEMENT = "post_assessment_engagement"
const val SUGGESTIONS ="recommendations_engagement"
const val INTRO_VIEWED = "intro_viewed"
const val INTRO_ENGAGEMENT = "intro_engagement"
const val FEATURE_STARTED = "feature_started"
const val THOUGHT_LOGGING_ENGAGEMENT = "thought_logging_engagement"
const val THOUGHT_PROVIDED = "thought_provided"
const val THOUGHT_TYPE_SELECTED = "thought_type_selected"





const val TIME_SPENT  = "time_spent"
const val REQUIRED  = "required"
const val USER_SKIP_INPUT  = "navigation_error"
const val  STOPPED_AT = "stopped_at"
const val IS_COMPLETED = "is_completed"

const val  PreMoodSelectionFragment = "pre_mood_selection"
const val  ShareWhatEffectingMoodFragment = "what_effecting_mood"
const val  EducationalFragment = "educational"
const val SpiritualFragment = "spiritual"

const val POST_MOOD_TRACKING = "post_mood_tracking"
const val PRE_SELECTED_MOOD = "pre_selected_mood"
const val POST_SELECTED_MOOD = "post_selected_mood"
const val MOOD = "mood"
const val SELECTED_MOOD = "selected_mood"
const val  CONGRATULATIONS = "congratulations"
const val  COMPARE_RESULT = "compare_result"
const val SESSION_DURATION = "session_duration"

const val INTRO1 = "intro1"
const val INTRO2 = "intro2"

const val REFLECT_ENGAGEMENT = "reflect_engagement"
const val CHOOSE_PATH_ENGAGEMENT = "choose_path_engagement"
const val THOUGHT_SENT = "thought_sent"
const val QUESTION_ANSWERED = "question_answered"
const val PATH_CHOSEN = "path_chosen"
const val ACTIVITY_SCHEDULED = "activity_scheduled"
const val RESPONSE_VIEWED = "response_viewed"
const val IS_THERE_RESPONSE = "is_there_response"
const val RESPONSE_ENGAGEMENT = "response_engagement"
const val RESET_THOUGHT_MYSELF = "reset_thought_myself"
const val REWRITE_THOUGHT = "rewrite_thought"
const val REFRAME_ENGAGEMENT = "reframe_engagement"
const val  THOUGHTS_RESTRUCTURING_ENGAGEMENT = "thoughts_restructuring_engagement"

